const LLMTokens = [
  process?.env?.["NEXT_PUBLIC_OPEN_AI_ORG_1"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_ORG_2"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_ORG_3"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_ORG_4"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_ORG_5"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_ORG_6"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_ORG_7"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_ORG_8"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_ORG_9"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_ORG_10"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_ORG_11"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_ORG_12"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_ORG_13"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_ORG_14"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_ORG_15"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_ORG_16"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_ORG_17"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_ORG_18"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_ORG_19"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_ORG_20"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_ORG_21"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_ORG_22"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_ORG_23"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_ORG_24"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_ORG_25"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_ORG_26"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_ORG_27"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_ORG_28"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_ORG_29"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_ORG_30"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_ORG_31"],
];

export default LLMTokens;
