const LLMTokens = [
  process?.env?.["NEXT_PUBLIC_OPEN_AI_KEY_1"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_KEY_2"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_KEY_3"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_KEY_4"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_KEY_5"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_KEY_6"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_KEY_7"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_KEY_8"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_KEY_9"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_KEY_10"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_KEY_11"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_KEY_12"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_KEY_13"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_KEY_14"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_KEY_15"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_KEY_16"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_KEY_17"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_KEY_18"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_KEY_19"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_KEY_20"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_KEY_21"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_KEY_22"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_KEY_23"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_KEY_24"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_KEY_25"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_KEY_26"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_KEY_27"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_KEY_28"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_KEY_29"],
  process?.env?.["NEXT_PUBLIC_OPEN_AI_KEY_30"],
];

export default LLMTokens;
